### PR TITLE
Fix parsing of gate arguments

### PR DESCRIPTION
**Pull request by a-komarev**
Fix parsing of gate arguments #54 for Laravel 5.1

### CODE REVIEW

**Comment by a-komarev** [comment]
@JosephSilber now it's your turn to unexpected issue closes? :+1:

**Comment by JosephSilber** [comment]
I clicked merge, then I clocked close.

But it didn't merge, because it's not letting me merge from my phone until Travis is done.

**Comment by a-komarev** [comment]
Thank you for fast issue resolving.

**Comment by JosephSilber** [comment]
I clicked merge, then I clicked close.

But it didn't merge, because it's not letting me merge from my phone until Travis is done.

image

**Pull request merged**
