### PR TITLE
Adding typecasts for attributes

### PR DESCRIPTION
**Pull request by Chrissi2812**
I ran into the issue that the properties were returned as strings from the database. (But only on the dedicated server at Siteground, not in localhost).

So I added typecasts fro non string attributes.

Is there a downside of adding these kind of typecasts?

-----
This might/will break custom UUID integrations into Bouncer, so users that use UUID have to override the `$cast` attribute

### CODE REVIEW

**Comment by a-komarev** [comment]
Not all people using IDs as integers. This will break hashed IDs or UUIDs.

**Comment by a-komarev** [comment]
This is barely related, but for the sake of example, [{json:api} spec says that all IDs MUST be strings](http://jsonapi.org/format/#document-resource-object-identification).

**Comment by Chrissi2812** [comment]
I removed the typecast for the ids as you said.
Didn't know before that ids should be strings in json...

**Comment by a-komarev** [comment]
That's not the requirement for all json documents. It's {json:api} standard. But since it's not great to expose auto-incrementing IDs to the clients and as alternative you may use Hashids, UUIDs or some kinds of similar stuff it's applicable for other mime\types as well.

**Comment by JosephSilber** [comment]
> Not all people using IDs as integers. This will break hashed IDs or UUIDs.

Most people use the default, so it's OK.

If you're using UUIDs, you have to tweak Bouncer's default migration. Not the end of the world to also have to [provide your own role and ability models](https://github.com/JosephSilber/bouncer/blob/master/readme.md#custom-models).

**Comment by JosephSilber** [comment]
Thanks :+1:

**Pull request merged**
