### PR TITLE
Support Mockery 1

### PR DESCRIPTION
**Pull request by carusogabriel**
Support [`Mockery 1`](https://github.com/mockery/mockery/releases/tag/1.0).

### CODE REVIEW

**Comment by JosephSilber** [comment]
Tests failing.

**Comment by carusogabriel** [comment]
I changed this PR to support, not complete migration. We still support Laravel `5.1` here :sweat_smile:

**Comment by JosephSilber** [comment]
I don't understand.

**Comment by carusogabriel** [comment]
`Mockery 1` requires `PHP 5.6`, and as we support `Laravel 5.1`, we can drop these versions.

**Comment by JosephSilber** [comment]
So we can't use Mockery 1 yet.

**Pull request closed without merging**
