### PR TITLE
Do not remove user's role and abilities when softDeleting

### PR DESCRIPTION
**Pull request by czapio92**
In relation to issue #485.

### CODE REVIEW

**Comment by JosephSilber** [comment]
Do you mind adding a test for this?

**Comment by emilas44** [comment]
the test fails only because of old php versions in travis file

**Comment by JosephSilber** [comment]
Can you rebase then?

**Comment by emilas44** [comment]
I don't know how to do that :D for real now!

**Comment by trawiasty** [comment]
Here's the rebased commit with additional tests:

https://github.com/JosephSilber/bouncer/compare/master...trawiasty:feature/soft-deletes-support

@czapio92 If you like the tests please rebase your's commit and cherry-pick mine.

**Comment by czapio92** [comment]
@trawiasty I like this tests, cherry picked.

@JosephSilber notice me.

**Comment by JosephSilber** [comment]
I rebased, tweaked and [merged](https://github.com/JosephSilber/bouncer/commit/2d58aac3e4ae6fdd29bb327c7c8cc84b65f36209).

**Comment by JosephSilber** [comment]
Thank you both :pray:

**Pull request closed without merging**
