### PR TITLE
Changed Raw queries to whereColumn so the fields will be escaped.

### PR DESCRIPTION
**Pull request by markdegrootnl**
When using custom table names with restricted characters (for instance :: in our project) the queries tail because whereRaw does not escape the table and column names. 
I've changed all the whereRaw functions to the equivalent whereColumn functions which do escape the field names.

### CODE REVIEW

**Comment by JosephSilber** [comment]
Tests failing.

**Comment by devonblzx** [comment]
I don't think whereColumn was introduced until Laravel 5.2.

**Comment by markdegrootnl** [comment]
I've changed the changes back to whereRaw queries, but escaped the table names.

**Comment by markdegrootnl** [comment]
Can you guys check and merge this?

**Comment by markdegrootnl** [comment]
Restrucured PR in #285

**Pull request closed without merging**
