### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 10.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/JosephSilber/bouncer/pull/618/commits/fe5f5e447941d5df7095226679c42c1e26c12a59?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/bouncer.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "silber/bouncer": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by Synchro** [comment]
These tests might pass if you run them again as L10 is now "stable". Would be good to see PHP 8.2 in the matrix too.

**Comment by JosephSilber** [comment]
@Synchro [released](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.1)!

**Comment by Synchro** [comment]
Fantastic, thank you!

**Pull request merged**
