### PR TITLE
Query Optimization - whereIn versus whereExists

### PR DESCRIPTION
**Pull request by xp-bar**
As a follow up to [Issue #459](https://github.com/JosephSilber/bouncer/issues/459):
The `whereExists` queries run by `@getRoleConstraint`, `@getAuthorityRoleConstraint`, `@getAuthorityConstraint` and `@getEveryoneConstraint` in`src/Database/Queries/Abilities.php` add a lot of unnecessary overhead, when the same could be accomplished using `whereIn`.

After running some speed tests, these changes appear to have increased performance by approximately 6x.

I've also validated that the models we have attached roles / permissions to return the same set of permissions / roles (ie. nothing is broken) when calling `src/BaseClipboard.php@getAbilities`, or validating an ability with `$model->can('my-awesome-ability', $argument);`.

Before the changes in this PR:

It took approximately 835 miliseconds (on average) to run:
```sql
select * from `abilities` where (
    exists (
        select * from `roles` inner join `permissions` on `roles`.`id` = `permissions`.`entity_id` where permissions.ability_id = abilities.id and `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and (
            exists (
                select * from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where assigned_roles.role_id = roles.id and `assigned_roles`.`entity_type` = ? and `users`.`id` = ?
            )
        )
    ) or exists (
        select * from `users` inner join `permissions` on `users`.`id` = `permissions`.`entity_id` where permissions.ability_id = abilities.id and `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and `users`.`id` = ?
    ) or exists (
        select * from `permissions` where permissions.ability_id = abilities.id and `permissions`.`forbidden` = ? and `entity_id` is null
    )
)
```

and it took approximately 868 miliseconds (on average) to run:
```sql
select * from `abilities` where (
    exists (
        select * from `roles` inner join `permissions` on `roles`.`id` = `permissions`.`entity_id` where permissions.ability_id = abilities.id and `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and (
            exists (
                select * from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where assigned_roles.role_id = roles.id and `assigned_roles`.`entity_type` = ? and `users`.`id` = ?
            ) or `level` < (
                select max(level) from `roles` where exists (select * from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where assigned_roles.role_id = roles.id and `assigned_roles`.`entity_type` = ? and `users`.`id` = ?)
            )
        )
    ) or exists (
        select * from `users` inner join `permissions` on `users`.`id` = `permissions`.`entity_id` where permissions.ability_id = abilities.id and `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and `users`.`id` = ?
    ) or exists (
        select * from `permissions` where permissions.ability_id = abilities.id and `permissions`.`forbidden` = ? and `entity_id` is null
    )
)
```

Versus after these changes:
from 
```php
$query->whereExists(static::getRoleConstraint($authority, $allowed));
$query->orWhereExists(static::getAuthorityConstraint($authority, $allowed));
$query->orWhereExists(static::getEveryoneConstraint($allowed));
```
to
```php
$abilities = Models::table('abilities');
$query->whereIn("{$abilities}.id", static::getRoleConstraint($authority, $allowed));
$query->orWhereIn("{$abilities}.id", static::getAuthorityConstraint($authority, $allowed));
$query->orWhereIn("{$abilities}.id", static::getEveryoneConstraint($allowed));
```
(plus the rest of this PR)

It took 114 miliseconds (on average) to run:
```sql
select * from `abilities` where (
    `abilities`.`id` in (
        select `permissions`.`ability_id` from `roles` inner join `permissions` on `roles`.`id` = `permissions`.`entity_id` where `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and (
            `roles`.`id` in (
                select `assigned_roles`.`role_id` from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where `assigned_roles`.`entity_type` = ? and `users`.`id` = ?
            )
        )
    ) or `abilities`.`id` in (
        select `permissions`.`ability_id` from `users` inner join `permissions` on `users`.`id` = `permissions`.`entity_id` where `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and `users`.`id` = ?
    ) or `abilities`.`id` in (
        select `permissions`.`ability_id` from `permissions` where `permissions`.`forbidden` = ? and `entity_id` is null
    )
)
```

and it took 160 miliseconds (on average) to run:
```sql
select * from `abilities` where (
    `abilities`.`id` in (
        select `permissions`.`ability_id` from `roles` inner join `permissions` on `roles`.`id` = `permissions`.`entity_id` where `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and (
            `roles`.`id` in (
                select `assigned_roles`.`role_id` from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where `assigned_roles`.`entity_type` = ? and `users`.`id` = ?
            ) or `level` < (
                select max(level) from `roles` where `roles`.`id` in (
                    select `assigned_roles`.`role_id` from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where `assigned_roles`.`entity_type` = ? and `users`.`id` = ?
                )
            )
        )
    ) or `abilities`.`id` in (
        select `permissions`.`ability_id` from `users` inner join `permissions` on `users`.`id` = `permissions`.`entity_id` where `permissions`.`forbidden` = ? and `permissions`.`entity_type` = ? and `users`.`id` = ?
    ) or `abilities`.`id` in (
        select `permissions`.`ability_id` from `permissions` where `permissions`.`forbidden` = ? and `entity_id` is null
    )
)
```

Test output:
```
...............................................................  63 / 329 ( 19%)
............................................................... 126 / 329 ( 38%)
............................................................... 189 / 329 ( 57%)
............................................................... 252 / 329 ( 76%)
............................................................... 315 / 329 ( 95%)
..............

Time: 17.16 seconds, Memory: 18.00MB

OK (329 tests, 1042 assertions)
```

### CODE REVIEW

**Comment by JosephSilber** [comment]
Do you know why it's faster?

**Comment by xp-bar** [comment]
My understanding is that `EXISTS` is typically faster when the results of the subquery are very large (since it stops searching after finding one result) whereas `WHERE IN` is typically faster if the results of your subquery is small (since the subquery runs once, vs `EXISTS` which runs once per row).

For my use case, it makes sense that `WHERE IN` is faster (lots of users, few permissions) but this may not be the case for everyone

**Comment by xp-bar** [comment]
I'll pull in `master` and retest to confirm again.

**Comment by JosephSilber** [comment]
Do you still plan on revisiting this?

**Comment by xp-bar** [comment]
My apologies - when I said I would pull and retest master, I pulled and retested master, and then didn't leave a comment saying I had done so

Since it's been a bit, I'll do it again sometime this week and get back to you.

Cheers!

**Comment by xp-bar** [comment]
Hey again. I don't know if I'll get a chance to revisit this anytime soon, given how long it's been.

I can close this PR, and re-open a new one with the changes if I ever get a chance to double back on this.

**Pull request closed without merging**
