### PR TITLE
Modified

### PR DESCRIPTION
**Pull request by AironDev**
made minor modifications : [added description property to Role and Ability models and migrations]

### CODE REVIEW

**Comment by AironDev** [comment]
Please ignore, it was intended for my fork - 
I want to add some hacks then point my composer to update from my forked

**Comment by JosephSilber** [comment]
FYI none of this requires you to fork Bouncer.

1. The migration file is published to your own app, so you can do with it whatever you want.

2. You can [use you own Role and Ability models](https://github.com/JosephSilber/bouncer/blob/master/readme.md#custom-models), which lets you tweak the tillable properties however you want.

**Comment by AironDev** [comment]
Ooh that will be great - how can I use my own Role and Ability model ?

**Comment by AironDev** [comment]
I seen it in  the docs - I will revert my implementation,
 Thanks

**Pull request closed without merging**
